/********************************************************************
* dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtabledict();
extern void G__cpp_setup_inheritancedict();
extern void G__cpp_setup_typetabledict();
extern void G__cpp_setup_memvardict();
extern void G__cpp_setup_globaldict();
extern void G__cpp_setup_memfuncdict();
extern void G__cpp_setup_funcdict();
extern void G__set_cpp_environmentdict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "JSON.h"
#include "alcaPhiSym_tree_v3.h"
#include "createHistoryPlots.h"
#include "lumiIntervals.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__dictLN_TString;
extern G__linked_taginfo G__dictLN_vectorlEboolcOallocatorlEboolgRsPgR;
extern G__linked_taginfo G__dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dictLN_pairlEintcOintgR;
extern G__linked_taginfo G__dictLN_JSON;
extern G__linked_taginfo G__dictLN_vectorlEpairlEintcOintgRcOallocatorlEpairlEintcOintgRsPgRsPgR;
extern G__linked_taginfo G__dictLN_reverse_iteratorlEvectorlEpairlEintcOintgRcOallocatorlEpairlEintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dictLN_maplEintcOvectorlEpairlEintcOintgRcOallocatorlEpairlEintcOintgRsPgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEpairlEintcOintgRcOallocatorlEpairlEintcOintgRsPgRsPgRsPgRsPgRsPgR;
extern G__linked_taginfo G__dictLN_pairlEintcOvectorlEpairlEintcOintgRcOallocatorlEpairlEintcOintgRsPgRsPgRsPgR;
extern G__linked_taginfo G__dictLN_maplEintcOvectorlEpairlEintcOintgRcOallocatorlEpairlEintcOintgRsPgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlEpairlEintcOintgRcOallocatorlEpairlEintcOintgRsPgRsPgRsPgRsPgRsPgRcLcLiterator;
extern G__linked_taginfo G__dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__dictLN_TTree;
extern G__linked_taginfo G__dictLN_TBranch;
extern G__linked_taginfo G__dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__dictLN_alcaPhiSym_tree_v3;
extern G__linked_taginfo G__dictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__dictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dictLN_lumiIntervals;
extern G__linked_taginfo G__dictLN_lumiIntervalscLcLrunLS;
extern G__linked_taginfo G__dictLN_pairlElumiIntervalscLcLrunLScOlumiIntervalscLcLrunLSgR;
extern G__linked_taginfo G__dictLN_vectorlEpairlElumiIntervalscLcLrunLScOlumiIntervalscLcLrunLSgRcOallocatorlEpairlElumiIntervalscLcLrunLScOlumiIntervalscLcLrunLSgRsPgRsPgR;
extern G__linked_taginfo G__dictLN_reverse_iteratorlEvectorlEpairlElumiIntervalscLcLrunLScOlumiIntervalscLcLrunLSgRcOallocatorlEpairlElumiIntervalscLcLrunLScOlumiIntervalscLcLrunLSgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__dictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dictLN_createHistoryPlots;

/* STUB derived class for protected member access */
